### ISSUE TITLE
Missing files

### ISSUE THREAD

**Issue by PoddsMind** [NHPatterson/regToolboxMSRC#1]
Hi there, 

I followed all the steps, that's provided. 
But I think u missed to push the python file ( `reg_tlbx_gui.py`) for GUI. 

As well for the below step, there is no `MSM_config.yaml` for the configuration file.
`python /regtoolboxMSRC/register_MSM.py MSM_config.yaml`

**Comment by NHPatterson** [comment]
Hello,

The ```reg_tlbx_gui.py``` is within the [```regtoolboxMSRC/GUI/``` folder](https://github.com/NHPatterson/regToolboxMSRC/blob/master/regToolboxMSRC/GUI/reg_tlbx_gui.py). It gets added to the python path during install. Usually this means in linux (ubuntu), if you have installed in a virtual environment, you can open the venv and then just run ```reg_tlbx_gui.py``` from the terminal. In windows, usually .py extensions end up associated with text editors or other software so you have to explicitly run ```python ../regtoolboxMSRC/GUI/reg_tlbx_gui.py```

The configuration files are meant when using the library from the command line. They specify inputs, registration parameters, and output destinations. It's an oversight on my part not to include some examples.. I'm going to update the ```README```, add some example data, and upload the full guide in short order (within the next few days) and hopefully this will clarify all your concerns

Thanks for your comment, I appreciate the feedback!
